name: Compilar mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

defaults:
  run:
    working-directory: cobblemon-custom-balls

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar y ejecutar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Compilar
        run: gradle build --stacktrace

      - name: Subir el jar compilado
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ccballs-jar
          path: cobblemon-custom-balls/build/libs/*.jar
          if-no-files-found: warn
